---
name: Validate PR
# description: Validate the pull request.
# https://github.com/amannn/action-semantic-pull-request

on:
  pull_request_target:
    types: [opened, edited, reopened]

permissions:
  pull-requests: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
